image: golang:1.13
pipelines:
  default:
    - step:
        script: 
            # Configure bitbucket pipelines
            - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
            - mkdir -pv "${PACKAGE_PATH}"
            - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"

            # Install dep
            - curl -o install-dep.sh https://raw.githubusercontent.com/golang/dep/master/install.sh
            - chmod +x install-dep.sh
            - ./install-dep.sh

            # Install
            - cd "${PACKAGE_PATH}"
            - dep ensure -v

            # Test
            - dep status -v
            - go test -v ./unittest/...
